[project]
name = "fmt"

git_repo = "fmtlib/fmt"

mokai_toml = """"
[project]
name = "fmt"
description = "A modern formatting library"
authors = ["Victor Zverovich"]
license = "MIT"
homepage = "[https://github.com/fmtlib/fmt](https://github.com/fmtlib/fmt)"
version_from = { file = "include/fmt/base.h", pattern = "FMT_VERSION ([0-9]+)([0-9][0-9])([0-9][0-9])" }
cpp_version = "c++11"
include_dirs = ["include"]

[options]
FMT_OS = true
FMT_UNICODE = true
FMT_PEDANTIC = false
FMT_WERROR = false

[property_group.gcc_pedantic_base]
condition = "compiler == gcc"
defines = []
flags = [
"-pedantic-errors", "-Wall", "-Wextra", "-pedantic", "-Wold-style-cast",
"-Wundef", "-Wredundant-decls", "-Wwrite-strings", "-Wpointer-arith",
"-Wcast-qual", "-Wformat=2", "-Wmissing-include-dirs", "-Wcast-align",
"-Wctor-dtor-privacy", "-Wdisabled-optimization", "-Winvalid-pch",
"-Woverloaded-virtual", "-Wconversion", "-Wno-ctor-dtor-privacy",
"-Wno-format-nonliteral"
]

[property_group.gcc_pedantic_modern]
condition = "compiler == gcc && compiler_version >= 5.0"
defines = []
flags = [
"-Wdouble-promotion", "-Wtrampolines", "-Wzero-as-null-pointer-constant",
"-Wuseless-cast", "-Wvector-operation-performance", "-Wsized-deallocation",
"-Wshadow"
]

[property_group.gcc_pedantic_post6]
condition = "compiler == gcc && compiler_version >= 6.0"
defines = []
flags = ["-Wshift-overflow=2", "-Wduplicated-cond"]

[property_group.clang_pedantic]
condition = "compiler == clang"
defines = []
flags = [
"-Wall", "-Wextra", "-pedantic", "-Wconversion", "-Wundef",
"-Wdeprecated", "-Wweak-vtables", "-Wshadow", "-Wno-gnu-zero-variadic-macro-arguments"
]

[property_group.msvc_pedantic]
condition = "compiler == msvc"
defines = []
flags = ["/W3"]

[target.fmt]
type = "static_library"
sources = ["src/format.cc"]
include_dirs = ["include"]
flags = []
properties = []
depends_on = []

[[target.fmt.sources_if]]
condition = "options.FMT_OS == true"
patterns = ["src/os.cc"]

[[target.fmt.properties_if]]
condition = "target_type == shared_library"
defines = ["FMT_LIB_EXPORT=1", "FMT_SHARED=1"]

[[target.fmt.properties_if]]
condition = "options.FMT_OS == false"
defines = ["FMT_OS=0"]

[[target.fmt.properties_if]]
condition = "compiler == msvc && options.FMT_UNICODE == false"
defines = ["FMT_UNICODE=0"]

[[target.fmt.properties_if]]
condition = "options.FMT_PEDANTIC == true"
defines = ["@gcc_pedantic_base", "@gcc_pedantic_modern", "@gcc_pedantic_post6", "@clang_pedantic", "@msvc_pedantic"]

[[target.fmt.flags_if]]
condition = "options.FMT_WERROR == true && compiler != msvc"
flags = ["-Werror"]

[[target.fmt.flags_if]]
condition = "options.FMT_WERROR == true && compiler == msvc"
flags = ["/WX"]

[[target.fmt.flags_if]]
condition = "compiler == msvc && options.FMT_UNICODE == true"
flags = ["/utf-8"]

[exports]
default_targets = ["fmt"]
include_dirs = ["include"]
defines_required = []

[exports.profile.core]
targets = ["fmt"]
"""
