[project]
name = "nlohmannjson"

git_repo = "nlohmann/json"

[recipes]
"latest" = """"
[project]
name = "json"
description = "JSON for Modern C++"

[exports]
default_targets = ["json_interface"]
include_dirs = ["include"]

[target.json_interface]
type = "static_library" 
sources = []
include_dirs = ["include"]
"""
